name: Farewall Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.FIREWALL_THEME_API_URL }}
          api-key: ${{ secrets.FIREWALL_THEME_API_KEY }}
