
name: Firewall Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./
      - name: Farewall Theme
        with:
          api-url: ${{ secrets.FIREWALL_THEME_API_URL }}
          api-key: ${{ secrets.FIREWALL_THEME_API_KEY }}